name: CI
on:
  push:
  workflow_dispatch:

jobs:
  base:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5

      - run: |
          echo todo
    #     ./build.sh
    #     podman save --quiet -o ${{ runner.temp }}/myimage.tar localhost/abstract-lfs-builder

    # - name: Upload artifact
    #   uses: actions/upload-artifact@v5
    #   with:
    #     name: myimage
    #     path: ${{ runner.temp }}/myimage.tar

  glibc:
    runs-on: ubuntu-24.04
    needs:
      - base
    steps:
      - uses: actions/checkout@v5

      - name: Get Cache key
        id: get_key
        run: |
          source glibc/env.sh
          echo "package=$PACKAGE" >> $GITHUB_OUTPUT
          echo "build_script_sum=$(md5sum build-glibc.sh | cut -d ' ' -f 1)" >> $GITHUB_OUTPUT

      - name: Cache
        id: cache-build
        uses: actions/cache@v4
        with:
          path: rootfs
          key: ${{ steps.get_key.outputs.package }}-${{ steps.get_key.outputs.build_script_sum }}

      - name: Build
        if: steps.cache-build.outputs.cache-hit != 'true'
        run: |
          ./build-glibc.sh

      - name: Tar files to preserve permissions
        run: tar cvf glibc.tar rootfs/*

      - name: Upload Package
        uses: actions/upload-artifact@v5
        with:
          name: package-glibc
          path: glibc.tar

  build:
    runs-on: ubuntu-24.04
    continue-on-error: true
    needs:
      - glibc

    strategy:
      fail-fast: false
      matrix:
        package:
          - acl
          - attr
          - bash
          - coreutils
          - e2fsprogs
          - kmod
          - systemd
          - util-linux
          - xz
          - zlib
          - zstd

    steps:
      - uses: actions/checkout@v5

      # - name: Download artifact
      #   uses: actions/download-artifact@v6
      #   with:
      #     name: myimage
      #     path: ${{ runner.temp }}

      # - name: Load image
      #   run: |
      #     podman load --input ${{ runner.temp }}/myimage.tar
      #     podman image ls -a

      - name: Download glibc
        uses: actions/download-artifact@v6
        with:
          name: package-glibc
          path: packages

      - run: find packages -name '*.tar'

      - run: find packages -name '*.tar' -exec tar xf {} \;
      - run: mv rootfs libs

      - run: |
          # wget https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-6.17.7.tar.xz
          # tar xf linux-6.17.7.tar.xz

          sudo apt-get -y install linux-headers-$(uname -r) build-essential
          cp -r /usr/include/linux libs/include
          cp -r /usr/include/asm /libs/include

          GCC_INCLUDE=$(gcc -print-file-name=include)
          cp -r $GCC_INCLUDE/* /usr/local/libs/include

      - run: find libs

      - name: Get Cache key
        id: get_key
        run: |
          source ${{ matrix.package }}/env.sh
          echo "package=$PACKAGE" >> $GITHUB_OUTPUT
          echo "build_script_sum=$(md5sum build-${{ matrix.package }}.sh | cut -d ' ' -f 1)" >> $GITHUB_OUTPUT

      - name: Cache
        id: cache-build
        uses: actions/cache@v4
        with:
          path: rootfs
          key: ${{ steps.get_key.outputs.package }}-${{ steps.get_key.outputs.build_script_sum }}

      - name: Build
        if: steps.cache-build.outputs.cache-hit != 'true'
        run: |
          ./build-${{ matrix.package }}.sh

      - name: Tar files to preserve permissions
        run: tar cvf ${{ matrix.package }}.tar rootfs/*

      - name: Upload Package
        uses: actions/upload-artifact@v5
        with:
          name: package-${{ matrix.package }}
          path: ${{ matrix.package }}.tar

  rootfs:
    runs-on: ubuntu-24.04
    needs:
      - build
    steps:
      - uses: actions/checkout@v5
      - uses: actions/download-artifact@v6
        with:
          path: packages

      - run: find packages -name '*.tar'

      - run: find packages -name '*.tar' -exec tar xf {} \;

      - name: Display structure of downloaded files
        run: find rootfs

      - run: mkdir -p output

      - name: Create disk image
        run: |
            podman build -t rootfs-builder -f rootfs.Containerfile .
            podman run --volume "$PWD"/rootfs:/usr/local/src --volume "$PWD"/output:/usr/local/output rootfs-builder /usr/local/bin/build-rootfs.sh

      - name: Upload rootfs
        uses: actions/upload-artifact@v5
        with:
          name: rootfs-dir
          path: rootfs

      - name: Upload rootfs.ext4
        uses: actions/upload-artifact@v5
        with:
          name: rootfs.ext4
          path: output/rootfs.ext4
