name: CI
on:
  push:
  workflow_dispatch:

jobs:
  base:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - run: |
          echo todo
    #     ./build.sh
    #     podman save --quiet -o ${{ runner.temp }}/myimage.tar localhost/abstract-lfs-builder

    # - name: Upload artifact
    #   uses: actions/upload-artifact@v5
    #   with:
    #     name: myimage
    #     path: ${{ runner.temp }}/myimage.tar

  build:
    runs-on: ubuntu-24.04
    continue-on-error: true
    needs:
      - base

    strategy:
      fail-fast: false
      matrix:
        package:
          - acl
          - attr
          - bash
          - coreutils
          - e2fsprogs
          - glibc
          - kmod
          - systemd
          - util-linux
          - xz
          - zlib
          - zstd

    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      # - name: Download artifact
      #   uses: actions/download-artifact@v6
      #   with:
      #     name: myimage
      #     path: ${{ runner.temp }}

      # - name: Load image
      #   run: |
      #     podman load --input ${{ runner.temp }}/myimage.tar
      #     podman image ls -a

      - name: Get Cache key
        id: get_key
        run: |
          source ${{ matrix.package }}/env.sh
          echo "package=$PACKAGE" >> $GITHUB_OUTPUT
          echo "build_script_sum=$(md5sum build-${{ matrix.package }}.sh | cut -d ' ' -f 1)" >> $GITHUB_OUTPUT

      - name: Cache
        id: cache-build
        uses: actions/cache@8b402f58fbc84540c8b491a91e594a4576fec3d7 # v5.0.2
        with:
          path: rootfs
          key: ${{ steps.get_key.outputs.package }}-${{ steps.get_key.outputs.build_script_sum }}

      - name: Build
        if: steps.cache-build.outputs.cache-hit != 'true'
        run: |
          ./build-${{ matrix.package }}.sh

      - name: Tar files to preserve permissions
        run: tar cvf ${{ matrix.package }}.tar rootfs/*

      - name: Upload Package
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: package-${{ matrix.package }}
          path: ${{ matrix.package }}.tar

  rootfs:
    runs-on: ubuntu-24.04
    needs:
      - build
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
        with:
          path: packages

      - run: find packages -name '*.tar' -exec tar xf {} \;

      - name: Display structure of downloaded files
        run: find rootfs

      - run: mkdir -p output

      - name: Create disk image
        run: |
            podman build -t rootfs-builder -f rootfs.Containerfile .
            podman run --volume "$PWD"/rootfs:/usr/local/src --volume "$PWD"/output:/usr/local/output rootfs-builder /usr/local/bin/build-rootfs.sh

      - name: Upload rootfs
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: rootfs-dir
          path: rootfs

      - name: Upload rootfs.ext4
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: rootfs.ext4
          path: output/rootfs.ext4
